apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      serviceAccountName: default
      containers:
      - name: docs
        image: registry.rydersel.cloud/docs
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docs
  namespace: default
spec:
  type: NodePort
  selector:
    app: docs
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30083
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: docs.rydersel.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docs
            port:
              number: 80
  tls:
    - hosts:
        - docs.rydersel.cloud
      secretName: wildcard-domain-certificate
